#! /bin/sh

gcc -g -Wall -o test_delta_eof.test test_delta_eof.c -I.. -L../.libs/ -lrsync
echo '======================================================================='
echo '  very small input (0 bytes), very small delta - 5 bytes'

./test_delta_eof.test 0
echo
echo
echo '======================================================================='
echo '  large input (2e6 bytes), delta of 6844 bytes'
./test_delta_eof.test 2000000
