name: continuous integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        compiler: [clang, gcc]
        options: [""]
        include:
          - os: windows-2019
            compiler: cl.exe
          - os: ubuntu-20.04
            compiler: gcc
            options: "-G Ninja"
          - os: ubuntu-20.04
            compiler: gcc
            options: "-D BUILD_SHARED_LIBS=OFF"
          - os: ubuntu-20.04
            compiler: gcc
            options: "-D BUILD_RDIFF=OFF"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install package dependencies
        if: startsWith( matrix.os, 'ubuntu' )
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake libpopt-dev doxygen ninja-build

      - name: Install package dependencies
        if: startsWith( matrix.os, 'macos' )
        run: |
          brew install cmake popt doxygen ninja

      - name: Configure
        env:
          CMAKE_OPTIONS: ${{ matrix.options }} -D CMAKE_C_COMPILER=${{ matrix.compiler }}
        run: |
          cmake $CMAKE_OPTIONS .

      - name: Build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          cmake --build . --target check

      - name: Document
        if: contains( matrix.options, '-G Ninja' )
        run: |
          ninja doc
